name: secrets workflow
run-name: secrets
on:
 push
jobs:
  echo-build:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: run script
      env:
       MY_SECRET: $ {{ secrets.reponame }}
       run: ./script.sh

      
