name: secrets workflow
run-name: secrets
on:
 push:
 workflow_dispatch:
  inputs:
   manual:
    type: string
    description: "choose the branch"
    required: true
   
jobs:
  echo-build:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: run script
      env:
       MY_SECRET: $ {{ secrets.reponame }}
      run: chmod +x ./.github/workflows/srcipt.sh

      
